### ISSUE TITLE
Question about Fabric port

### ISSUE THREAD

**Issue by vico93** [Autovw/MoreConcrete#8]
Does a Fabric port is in the plans?

And if not, can other modder port it themselves?

**Comment by Autovw** [comment]
An actual Fabric version has been worked on in the past. However, if you look on CurseForge you can see there are already lots of similar mods already available for both Fabric and Forge. (See [Concrete Plus (Fabric)](https://www.curseforge.com/minecraft/mc-mods/concrete-plus) for example)

Because of this I decided against releasing a Fabric version. I'd say it's a little bit unfair to the author of the mod I mentioned if I were to suddenly release a Fabric version.

However, if there ever turns out to be a need for a Fabric version (for example: an alternative becomes abandoned for some reason) I would like to release a Fabric version of the mod myself.
